<?php
/**
 * Template file for Magebit_PageListWidget.
 *
 * This file is responsible for rendering the Page List widget, including its title
 * and a list of pages based on the selected options in the widget configuration.
 *
 * @var \Magebit\PageListWidget\Block\Widget\PageList $block
 */

    $pages = $block->getPages();
?>
<div class="magebit-page-list-widget">
    <?php if ($title = $block->getTitle()): ?>
        <h2 class="page-list-title"><?= $block->escapeHtml($title) ?></h2>
    <?php endif; ?>

    <?php if ($pages->getSize()): ?>
        <ul class="page-list">
            <?php foreach ($pages as $page): ?>
                <li class="page-item">
                    <a href="<?= $block->escapeUrl($block->getUrl($page->getIdentifier())) ?>"><?= $block->escapeHtml($page->getTitle()) ?></a>
                </li>
            <?php endforeach; ?>
        </ul>
    <?php else: ?>
        <p><?= __('No pages available.') ?></p>
    <?php endif; ?>
</div>

