<?php
/**
 * @copyright Copyright (c) 2024 Magebit (https://magebit.com)
 * @author    Magebit <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 */
/** @var \Magento\Catalog\Block\Product\View\Attributes $block */
/** @var \Magento\Catalog\Model\Product $product */
$product = $block->getProduct();
$attributes = $product->getAttributes();
$catalogHelper = $this->helper('Magento\Catalog\Helper\Output');
// Attributes to display
$displayAttributes = ['dimensions', 'color', 'material'];
?>

<div class="product-details">
    <?php foreach ($displayAttributes as $code): ?>
        <?php if (isset($attributes[$code])): ?>
            <?php $attribute = $attributes[$code];?>
            <div class="detail-item">
                <li><strong><?= $attribute->getFrontendLabel() ?>:</strong>
                    <?= $attribute->getFrontend()->getValue($product) ?></li>
            </div>
        <?php endif; ?>
    <?php endforeach; ?>
    <div class="short-description">
        <?= $attributes['short_description']->getFrontend()->getValue($product) ?>
    </div>
</div>
