<?php
/**
 * @copyright Copyright (c) 2024 Magebit (https://magebit.com)
 * @author    Magebit <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 */
declare(strict_types=1);

use Magebit\Learning\Block\Product\View\ProductAttributes;
use Magento\Framework\Escaper;

/** @var ProductAttributes $block */
/** @var Escaper $escaper */

$product = $block->getProduct();
$attributes = $product->getAttributes();
?>

<div class="product-details">
    <?php $filteredAttributes = $block->getFilteredAttributes(); ?>
    <?php if (!empty($filteredAttributes)): ?>
        <?php foreach ($filteredAttributes as $attribute): ?>
            <div class="detail-item">
                <strong><?= $escaper->escapeHtml($attribute->getFrontendLabel()) ?>:</strong>
                <?= $escaper->escapeHtml($block->getAttributeValue($attribute, $block->getProduct())) ?>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
    <div class="short-description">
        <?= $escaper->escapeHtml($attributes['short_description']->getFrontend()->getValue($product)) ?>
    </div>
</div>
