<?php
/**
 * @copyright Copyright (c) 2024 Magebit (https://magebit.com)
 * @author    Magebit <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 */
declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Related;
use Magento\Framework\Escaper;


/** @var Escaper $escaper */
/** @var Related $block */
$products = $block->getItems();
?>

<div class="block-related">
    <div class="related-header"><?= $escaper->escapeHtml(__('Related products')) ?></div>
    <div class="related-product-grid">
        <?php foreach ($products as $product): ?>
            <div class="related-product">
                <img class="related-product-image"
                     src="<?= $escaper->escapeUrl($block->getImage($product, 'product_page_image_large')->getImageUrl()) ?>"
                     alt="<?= $escaper->escapeHtml($product->getName()) ?>" />
                <div class="related-product-info">
                    <div class="related-product-name"><?= $escaper->escapeHtml($product->getName()) ?></div>
                    <div class="related-product-reviews"><?= $block->getReviewsSummaryHtml($product, 'short') ?></div>
                    <div class="related-product-price"><?= $escaper->escapeHtml('$' . number_format($product->getPrice(), 2)) ?></div>
                    <form action="<?= $escaper->escapeUrl($block->getAddToCartUrl($product)) ?>" method="post">
                        <button type="submit" class="addtocart-btn addtocart-button-visibility">
                            <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                        </button>
                    </form>
                </div>
            </div>
        <?php endforeach; ?>
    </div>
</div>
