<?php
/**
 * @copyright Copyright (c) 2024 Magebit (https://magebit.com)
 * @author    Magebit <info@magebit.com>
 * @license   GNU General Public License ("GPL") v3.0
 */
declare(strict_types=1);

use Magento\Catalog\Block\Product\ProductList\Upsell;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
/** @var Upsell $block */

$products = $block->getItems();
?>

<div>
    <div class="upsell-header">
        <?= $escaper->escapeHtml(__('We found other products you might like!')) ?>
    </div>
    <?php foreach ($products as $product): ?>
        <div class="upsell-product">
            <img class="upsell-image"
                 src="<?= $escaper->escapeUrl($block->getImage($product, 'product_page_image_small')->getImageUrl()) ?>"
                 alt="<?= $escaper->escapeHtml($product->getName()) ?>" />
            <div class="upsell-product-info">
                <div class="upsell-product-name"><?= $escaper->escapeHtml($product->getName()) ?></div>
                <div class="upsell-reviews"><?= $block->getReviewsSummaryHtml($product, 'short') ?></div>
                <div class="upsell-product-price"><?= $escaper->escapeHtml('$' . number_format((float)$product->getPrice(), 2)) ?></div>
            </div>
            <a class="upsell-product-link" href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>">
                <?= $escaper->escapeHtml(__('View Product')) ?>
            </a>
        </div>
    <?php endforeach; ?>
</div>
